// Objective-C API for talking to tphone_sdk_core/tphone_sdk_core_callback Go package.
//   gobind -lang=objc tphone_sdk_core/tphone_sdk_core_callback
//
// File is generated by gobind. Do not edit.

#ifndef __Tphone_sdk_core_callback_H__
#define __Tphone_sdk_core_callback_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol Tphone_sdk_core_callbackTBaseCallback;
@class Tphone_sdk_core_callbackTBaseCallback;
@protocol Tphone_sdk_core_callbackTIncomingMessageListener;
@class Tphone_sdk_core_callbackTIncomingMessageListener;
@protocol Tphone_sdk_core_callbackTIncomingUpdateSockJsUrlListener;
@class Tphone_sdk_core_callbackTIncomingUpdateSockJsUrlListener;
@protocol Tphone_sdk_core_callbackTLoginMessageListener;
@class Tphone_sdk_core_callbackTLoginMessageListener;
@protocol Tphone_sdk_core_callbackTOnEventListener;
@class Tphone_sdk_core_callbackTOnEventListener;

@protocol Tphone_sdk_core_callbackTBaseCallback <NSObject>
- (void)onError:(int32_t)errCode errMsg:(NSString* _Nullable)errMsg;
- (void)onSuccess:(NSString* _Nullable)data;
@end

@protocol Tphone_sdk_core_callbackTIncomingMessageListener <NSObject>
- (void)onMessage:(NSString* _Nullable)message;
- (void)onUpdateSessionId:(NSString* _Nullable)session;
@end

@protocol Tphone_sdk_core_callbackTIncomingUpdateSockJsUrlListener <NSObject>
- (void)onUpdateUrl:(NSString* _Nullable)message;
@end

@protocol Tphone_sdk_core_callbackTLoginMessageListener <NSObject>
- (void)onError:(int32_t)errCode errMsg:(NSString* _Nullable)errMsg;
- (void)onSuccess:(NSString* _Nullable)message;
- (void)onWebSocketMessage:(NSString* _Nullable)message;
@end

@protocol Tphone_sdk_core_callbackTOnEventListener <NSObject>
- (void)onEventChange:(NSString* _Nullable)event message:(NSString* _Nullable)message;
- (NSString* _Nonnull)onGetConfig:(NSString* _Nullable)typeName;
@end

@class Tphone_sdk_core_callbackTBaseCallback;

@class Tphone_sdk_core_callbackTIncomingMessageListener;

@class Tphone_sdk_core_callbackTIncomingUpdateSockJsUrlListener;

@class Tphone_sdk_core_callbackTLoginMessageListener;

@class Tphone_sdk_core_callbackTOnEventListener;

@interface Tphone_sdk_core_callbackTBaseCallback : NSObject <goSeqRefInterface, Tphone_sdk_core_callbackTBaseCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(int32_t)errCode errMsg:(NSString* _Nullable)errMsg;
- (void)onSuccess:(NSString* _Nullable)data;
@end

@interface Tphone_sdk_core_callbackTIncomingMessageListener : NSObject <goSeqRefInterface, Tphone_sdk_core_callbackTIncomingMessageListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onMessage:(NSString* _Nullable)message;
- (void)onUpdateSessionId:(NSString* _Nullable)session;
@end

@interface Tphone_sdk_core_callbackTIncomingUpdateSockJsUrlListener : NSObject <goSeqRefInterface, Tphone_sdk_core_callbackTIncomingUpdateSockJsUrlListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onUpdateUrl:(NSString* _Nullable)message;
@end

@interface Tphone_sdk_core_callbackTLoginMessageListener : NSObject <goSeqRefInterface, Tphone_sdk_core_callbackTLoginMessageListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onError:(int32_t)errCode errMsg:(NSString* _Nullable)errMsg;
- (void)onSuccess:(NSString* _Nullable)message;
- (void)onWebSocketMessage:(NSString* _Nullable)message;
@end

@interface Tphone_sdk_core_callbackTOnEventListener : NSObject <goSeqRefInterface, Tphone_sdk_core_callbackTOnEventListener> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)onEventChange:(NSString* _Nullable)event message:(NSString* _Nullable)message;
- (NSString* _Nonnull)onGetConfig:(NSString* _Nullable)typeName;
@end

#endif
