
// Objective-C API for talking to the following Go packages
//
//	tphone_sdk_core/tphone_sdk_core
//	tphone_sdk_core/tphone_sdk_core_callback
//
// File is generated by gomobile bind. Do not edit.
#ifndef __TPhoneSDKCore_FRAMEWORK_H__
#define __TPhoneSDKCore_FRAMEWORK_H__

#include "Tphone_sdk_core.objc.h"
#include "Tphone_sdk_core_callback.objc.h"
#include "Universe.objc.h"

#endif
