// Objective-C API for talking to tphone_sdk_core/tphone_sdk_core Go package.
//   gobind -lang=objc tphone_sdk_core/tphone_sdk_core
//
// File is generated by gobind. Do not edit.

#ifndef __Tphone_sdk_core_H__
#define __Tphone_sdk_core_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Tphone_sdk_core_callback.objc.h"

@interface Tphone_sdk_core : NSObject
// skipped variable UserRouterMap with unsupported type: map[string]*tphone_sdk_core/internal/login.LoginMgr

// skipped variable UserSDKRwLock with unsupported type: sync.RWMutex

@end

/**
 * 坐席挂机接口
 */
FOUNDATION_EXPORT void Tphone_sdk_coreAgentUnlink(id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback);

FOUNDATION_EXPORT void Tphone_sdk_coreCall(NSString* _Nullable phoneNumber, NSString* _Nullable obClid, NSString* _Nullable requestUniqueId, NSString* _Nullable userField);

FOUNDATION_EXPORT void Tphone_sdk_coreChangePwd(NSString* _Nullable oldPassword, NSString* _Nullable newPassword, id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback);

FOUNDATION_EXPORT void Tphone_sdk_coreConfirmVerificationCode(NSString* _Nullable verificationCode, id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback);

FOUNDATION_EXPORT void Tphone_sdk_coreGetAgentSettings(id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback);

FOUNDATION_EXPORT void Tphone_sdk_coreGetAgentStatus(id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback);

// skipped function GetUserWorker with unsupported parameter or return types


FOUNDATION_EXPORT BOOL Tphone_sdk_coreInitSDK(NSString* _Nullable initOption);

FOUNDATION_EXPORT void Tphone_sdk_coreLoginTiPhone(NSString* _Nullable loginOption, id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback, id<Tphone_sdk_core_callbackTLoginMessageListener> _Nullable loginCb);

FOUNDATION_EXPORT void Tphone_sdk_coreLogoutTiPhone(id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback);

FOUNDATION_EXPORT void Tphone_sdk_corePreviewOutCall(NSString* _Nullable phoneNumber, NSString* _Nullable obClid, id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback);

/**
 * 原生判断无网或切网条件，之后调用此接口，目的是及时将go中的ws重置
 */
FOUNDATION_EXPORT void Tphone_sdk_coreResetWebSocket(void);

FOUNDATION_EXPORT void Tphone_sdk_coreRtcAuth(NSString* _Nullable loginOption, id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback);

FOUNDATION_EXPORT void Tphone_sdk_coreRtcLogin(NSString* _Nullable loginOption, id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback, id<Tphone_sdk_core_callbackTLoginMessageListener> _Nullable loginCb);

FOUNDATION_EXPORT void Tphone_sdk_coreRtcLogoutTiPhone(id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback);

FOUNDATION_EXPORT void Tphone_sdk_coreRtcRefreshAccessToken(NSString* _Nullable loginOption, id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback);

FOUNDATION_EXPORT NSString* _Nonnull Tphone_sdk_coreSdkVersion(void);

FOUNDATION_EXPORT void Tphone_sdk_coreSendCallOrUpdateMessage(NSString* _Nullable sdp, BOOL isRestart);

FOUNDATION_EXPORT void Tphone_sdk_coreSendHangupMessage(void);

FOUNDATION_EXPORT void Tphone_sdk_coreSendTrickleCandidateOrComplete(NSString* _Nullable candidateSDP, NSString* _Nullable candidateSdpMid, double sdpMLineIndex);

FOUNDATION_EXPORT void Tphone_sdk_coreSetAgentPause(NSString* _Nullable description, id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback);

FOUNDATION_EXPORT void Tphone_sdk_coreSetAgentUnPause(id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback);

FOUNDATION_EXPORT void Tphone_sdk_coreSetIncomingMessageListener(id<Tphone_sdk_core_callbackTIncomingMessageListener> _Nullable listener);

FOUNDATION_EXPORT void Tphone_sdk_coreSetOnEventListener(id<Tphone_sdk_core_callbackTOnEventListener> _Nullable listener);

FOUNDATION_EXPORT void Tphone_sdk_coreSetRTCIncomingMessageListener(NSString* _Nullable agentgwurl, NSString* _Nullable sessionKey, id<Tphone_sdk_core_callbackTIncomingMessageListener> _Nullable listener);

FOUNDATION_EXPORT void Tphone_sdk_coreSetTelExplicit(BOOL isTelExplicit);

FOUNDATION_EXPORT void Tphone_sdk_coreTransferCall(NSString* _Nullable requestUniqueId, id<Tphone_sdk_core_callbackTBaseCallback> _Nullable callback);

#endif
